<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=11"/>
<meta name="generator" content="Doxygen 1.12.0"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>My Project: Error handling</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<script type="text/javascript" src="clipboard.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="resize.js"></script>
<script type="text/javascript" src="cookie.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr id="projectrow">
  <td id="projectalign">
   <div id="projectname">My Project
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.12.0 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
var searchBox = new SearchBox("searchBox", "search/",'.html');
/* @license-end */
</script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
$(function() { codefold.init(0); });
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
$(function() {
  initMenu('',true,false,'search.php','Search',false);
  $(function() { init_search(); });
});
/* @license-end */
</script>
<div id="main-nav"></div>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
$(function(){ initResizable(false); });
/* @license-end */
</script>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<div id="MSearchResults">
<div class="SRPage">
<div id="SRIndex">
<div id="SRResults"></div>
<div class="SRStatus" id="Loading">Loading...</div>
<div class="SRStatus" id="Searching">Searching...</div>
<div class="SRStatus" id="NoMatches">No Matches</div>
</div>
</div>
</div>
</div>

</div><!-- top -->
<div id="doc-content">
<div><div class="header">
  <div class="headertitle"><div class="title">Error handling</div></div>
</div><!--header-->
<div class="contents">
<div class="textblock"><p><a class="anchor" id="autotoc_md7803"></a></p>
<p>Error handling represents one of the most important considerations when implementing a Node.js native add-on. When an error occurs in your C++ code you have to handle and dispatch it correctly. <b>node-addon-api</b> uses return values and JavaScript exceptions for error handling. You can choose return values or exception handling based on the mechanism that works best for your add-on.</p>
<p>The <code><a class="el" href="class_napi_1_1_error.html">Napi::Error</a></code> is a persistent reference (for more info see: <a class="el" href="md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_25babb8f4ee8ee92c1b4986368972009e.html"><code>Napi::ObjectReference</code></a>) to a JavaScript error object. Use of this class depends on whether C++ exceptions are enabled at compile time.</p>
<p>If C++ exceptions are enabled (for more info see: <a class="el" href="md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_266528d00135031cc477eae3ce7dfec6e.html">Setup</a>), then the <code><a class="el" href="class_napi_1_1_error.html">Napi::Error</a></code> class extends <code>std::exception</code> and enables integrated error-handling for C++ exceptions and JavaScript exceptions.</p>
<p>The following sections explain the approach for each case:</p>
<ul>
<li>Handling Errors With C++ Exceptions</li>
<li>Handling Errors Without C++ Exceptions</li>
</ul>
<p><a class="anchor" id="exceptions"></a></p>
<p>In most cases when an error occurs, the addon should do whatever clean is possible and then return to JavaScript so that they error can be propagated. In less frequent cases the addon may be able to recover from the error, clear the error and then continue.</p>
<h1><a class="anchor" id="autotoc_md7804"></a>
Handling Errors With C++ Exceptions</h1>
<p>When C++ exceptions are enabled try/catch can be used to catch exceptions thrown from calls to JavaScript and then they can either be handled or rethrown before returning from a native method.</p>
<p>If a node-addon-api call fails without executing any JavaScript code (for example due to an invalid argument), then node-addon-api automatically converts and throws the error as a C++ exception of type <code><a class="el" href="class_napi_1_1_error.html">Napi::Error</a></code>.</p>
<p>If a JavaScript function called by C++ code via node-addon-api throws a JavaScript exception, then node-addon-api automatically converts and throws it as a C++ exception of type <code><a class="el" href="namespace_napi.html">Napi</a>:Error</code> on return from the JavaScript code to the native method.</p>
<p>If a C++ exception of type <code><a class="el" href="class_napi_1_1_error.html">Napi::Error</a></code> escapes from a N-API C++ callback, then the N-API wrapper automatically converts and throws it as a JavaScript exception.</p>
<p>On return from a native method, node-addon-api will automatically convert a pending C++ exception to a JavaScript exception.</p>
<p>When C++ exceptions are enabled try/catch can be used to catch exceptions thrown from calls to JavaScript and then they can either be handled or rethrown before returning from a native method.</p>
<h1><a class="anchor" id="autotoc_md7805"></a>
Examples with C++ exceptions enabled</h1>
<h2><a class="anchor" id="autotoc_md7806"></a>
Throwing a C++ exception</h2>
<div class="fragment"><div class="line">Env env = ...</div>
<div class="line">throw Napi::Error::New(env, <span class="stringliteral">&quot;Example exception&quot;</span>);</div>
<div class="line"><span class="comment">// other C++ statements</span></div>
<div class="line"><span class="comment">// ...</span></div>
</div><!-- fragment --><p>The statements following the throw statement will not be executed. The exception will bubble up as a C++ exception of type <code><a class="el" href="class_napi_1_1_error.html">Napi::Error</a></code>, until it is either caught while still in C++, or else automatically propagated as a JavaScript exception when returning to JavaScript.</p>
<h2><a class="anchor" id="autotoc_md7807"></a>
Propagating a N-API C++ exception</h2>
<div class="fragment"><div class="line"><a class="code hl_class" href="class_napi_1_1_function.html">Napi::Function</a> jsFunctionThatThrows = someObj.<a class="code hl_function" href="class_napi_1_1_value.html#a9c1a9c4eca9617b0aafbe311c946982a">As</a>&lt;<a class="code hl_class" href="class_napi_1_1_function.html">Napi::Function</a>&gt;();</div>
<div class="line"><a class="code hl_class" href="class_napi_1_1_value.html">Napi::Value</a> result = jsFunctionThatThrows({ arg1, arg2 });</div>
<div class="line"><span class="comment">// other C++ statements</span></div>
<div class="line"><span class="comment">// ...</span></div>
<div class="ttc" id="aclass_napi_1_1_function_html"><div class="ttname"><a href="class_napi_1_1_function.html">Napi::Function</a></div><div class="ttdef"><b>Definition</b> napi.h:956</div></div>
<div class="ttc" id="aclass_napi_1_1_value_html"><div class="ttname"><a href="class_napi_1_1_value.html">Napi::Value</a></div><div class="ttdef"><b>Definition</b> napi.h:190</div></div>
<div class="ttc" id="aclass_napi_1_1_value_html_a9c1a9c4eca9617b0aafbe311c946982a"><div class="ttname"><a href="class_napi_1_1_value.html#a9c1a9c4eca9617b0aafbe311c946982a">Napi::Value::As</a></div><div class="ttdeci">T As() const</div><div class="ttdef"><b>Definition</b> napi-inl.h:469</div></div>
</div><!-- fragment --><p>The C++ statements following the call to the JavaScript function will not be executed. The exception will bubble up as a C++ exception of type <code><a class="el" href="class_napi_1_1_error.html">Napi::Error</a></code>, until it is either caught while still in C++, or else automatically propagated as a JavaScript exception when returning to JavaScript.</p>
<h2><a class="anchor" id="autotoc_md7808"></a>
Handling a N-API C++ exception</h2>
<div class="fragment"><div class="line"><a class="code hl_class" href="class_napi_1_1_function.html">Napi::Function</a> jsFunctionThatThrows = someObj.<a class="code hl_function" href="class_napi_1_1_value.html#a9c1a9c4eca9617b0aafbe311c946982a">As</a>&lt;<a class="code hl_class" href="class_napi_1_1_function.html">Napi::Function</a>&gt;();</div>
<div class="line"><a class="code hl_class" href="class_napi_1_1_value.html">Napi::Value</a> result;</div>
<div class="line"><span class="keywordflow">try</span> {</div>
<div class="line">    result = jsFunctionThatThrows({ arg1, arg2 });</div>
<div class="line">} <span class="keywordflow">catch</span> (<span class="keyword">const</span> Error&amp; e) {</div>
<div class="line">    cerr &lt;&lt; <span class="stringliteral">&quot;Caught JavaScript exception: &quot;</span> + e.what();</div>
<div class="line">}</div>
</div><!-- fragment --><p>Since the exception was caught here, it will not be propagated as a JavaScript exception.</p>
<p><a class="anchor" id="noexceptions"></a></p>
<h1><a class="anchor" id="autotoc_md7809"></a>
Handling Errors Without C++ Exceptions</h1>
<p>If C++ exceptions are disabled (for more info see: <a class="el" href="md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_266528d00135031cc477eae3ce7dfec6e.html">Setup</a>), then the <code><a class="el" href="class_napi_1_1_error.html">Napi::Error</a></code> class does not extend <code>std::exception</code>. This means that any calls to node-addon-api function do not throw a C++ exceptions. Instead, it raises <em>pending</em> JavaScript exceptions and returns an <em>empty</em> <code><a class="el" href="class_napi_1_1_value.html">Napi::Value</a></code>. The calling code should check <code>env.IsExceptionPending()</code> before attempting to use a returned value, and may use methods on the <code><a class="el" href="class_napi_1_1_env.html">Napi::Env</a></code> class to check for, get, and clear a pending JavaScript exception (for more info see: <a class="el" href="md__2_users_2hello_2_documents_2_git_hub_2finalproject-engine-drop-table-engines_2_engine_2src_29e67c9204cf2be24debd79122b6a3af1.html">Env</a>). If the pending exception is not cleared, it will be thrown when the native code returns to JavaScript.</p>
<h1><a class="anchor" id="autotoc_md7810"></a>
Examples with C++ exceptions disabled</h1>
<h2><a class="anchor" id="autotoc_md7811"></a>
Throwing a JS exception</h2>
<div class="fragment"><div class="line"><a class="code hl_class" href="class_napi_1_1_env.html">Napi::Env</a> env = ...</div>
<div class="line">Napi::Error::New(env, <span class="stringliteral">&quot;Example exception&quot;</span>).ThrowAsJavaScriptException();</div>
<div class="line"><span class="keywordflow">return</span>;</div>
<div class="ttc" id="aclass_napi_1_1_env_html"><div class="ttname"><a href="class_napi_1_1_env.html">Napi::Env</a></div><div class="ttdef"><b>Definition</b> napi.h:162</div></div>
</div><!-- fragment --><p>After throwing a JavaScript exception, the code should generally return immediately from the native callback, after performing any necessary cleanup.</p>
<h2><a class="anchor" id="autotoc_md7812"></a>
Propagating a N-API JS exception</h2>
<div class="fragment"><div class="line"><a class="code hl_class" href="class_napi_1_1_env.html">Napi::Env</a> env = ...</div>
<div class="line">Napi::Function jsFunctionThatThrows = someObj.<a class="code hl_function" href="class_napi_1_1_value.html#a9c1a9c4eca9617b0aafbe311c946982a">As</a>&lt;<a class="code hl_class" href="class_napi_1_1_function.html">Napi::Function</a>&gt;();</div>
<div class="line"><a class="code hl_class" href="class_napi_1_1_value.html">Napi::Value</a> result = jsFunctionThatThrows({ arg1, arg2 });</div>
<div class="line"><span class="keywordflow">if</span> (env.IsExceptionPending()) {</div>
<div class="line">    Error e = env.GetAndClearPendingException();</div>
<div class="line">    <span class="keywordflow">return</span> e.Value();</div>
<div class="line">}</div>
</div><!-- fragment --><p>If env.IsExceptionPending() returns true a JavaScript exception is pending. To let the exception propagate, the code should generally return immediately from the native callback, after performing any necessary cleanup.</p>
<h2><a class="anchor" id="autotoc_md7813"></a>
Handling a N-API JS exception</h2>
<div class="fragment"><div class="line"><a class="code hl_class" href="class_napi_1_1_env.html">Napi::Env</a> env = ...</div>
<div class="line">Napi::Function jsFunctionThatThrows = someObj.<a class="code hl_function" href="class_napi_1_1_value.html#a9c1a9c4eca9617b0aafbe311c946982a">As</a>&lt;<a class="code hl_class" href="class_napi_1_1_function.html">Napi::Function</a>&gt;();</div>
<div class="line"><a class="code hl_class" href="class_napi_1_1_value.html">Napi::Value</a> result = jsFunctionThatThrows({ arg1, arg2 });</div>
<div class="line"><span class="keywordflow">if</span> (env.IsExceptionPending()) {</div>
<div class="line">    <a class="code hl_class" href="class_napi_1_1_error.html">Napi::Error</a> e = env.GetAndClearPendingException();</div>
<div class="line">    cerr &lt;&lt; <span class="stringliteral">&quot;Caught JavaScript exception: &quot;</span> + e.Message();</div>
<div class="line">}</div>
<div class="ttc" id="aclass_napi_1_1_error_html"><div class="ttname"><a href="class_napi_1_1_error.html">Napi::Error</a></div><div class="ttdef"><b>Definition</b> napi.h:1283</div></div>
</div><!-- fragment --><p>Since the exception was cleared here, it will not be propagated as a JavaScript exception after the native callback returns.</p>
<h1><a class="anchor" id="autotoc_md7814"></a>
Calling N-API directly from a <b>node-addon-api</b> addon</h1>
<p><b>node-addon-api</b> provides macros for throwing errors in response to non-OK <code>napi_status</code> results when calling <a href="https://nodejs.org/docs/latest/api/n-api.html">N-API</a> functions from within a native addon. These macros are defined differently depending on whether C++ exceptions are enabled or not, but are available for use in either case.</p>
<h2><a class="anchor" id="autotoc_md7815"></a>
<code>NAPI_THROW(e, ...)</code></h2>
<p>This macro accepts a <code><a class="el" href="class_napi_1_1_error.html">Napi::Error</a></code>, throws it, and returns the value given as the last parameter. If C++ exceptions are enabled (by defining <code>NAPI_CPP_EXCEPTIONS</code> during the build), the return value will be ignored.</p>
<h2><a class="anchor" id="autotoc_md7816"></a>
<code>NAPI_THROW_IF_FAILED(env, status, ...)</code></h2>
<p>This macro accepts a <code><a class="el" href="class_napi_1_1_env.html">Napi::Env</a></code> and a <code>napi_status</code>. It constructs an error from the <code>napi_status</code>, throws it, and returns the value given as the last parameter. If C++ exceptions are enabled (by defining <code>NAPI_CPP_EXCEPTIONS</code> during the build), the return value will be ignored.</p>
<h2><a class="anchor" id="autotoc_md7817"></a>
<code>NAPI_THROW_IF_FAILED_VOID(env, status)</code></h2>
<p>This macro accepts a <code><a class="el" href="class_napi_1_1_env.html">Napi::Env</a></code> and a <code>napi_status</code>. It constructs an error from the <code>napi_status</code>, throws it, and returns.</p>
<h2><a class="anchor" id="autotoc_md7818"></a>
<code>NAPI_FATAL_IF_FAILED(status, location, message)</code></h2>
<p>This macro accepts a <code>napi_status</code>, a C string indicating the location where the error occurred, and a second C string for the message to display. </p>
</div></div><!-- contents -->
</div><!-- PageDoc -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.12.0
</small></address>
</div><!-- doc-content -->
</body>
</html>
